apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.service.name }}
